name: nv-h100

on:
  push:
    branches:
      - 'staging**'
    paths-ignore:
      - 'docs/**'
      - 'blogs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'blogs/**'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: [self-hosted, nvidia, h100]

    steps:
      - uses: actions/checkout@v3

      - name: Nvidia SMI
        run: |
          nvidia-smi -L

      - name: Load docker image
        run: |
          sudo docker exec deepspeed-github-ci /bin/bash

      - name: Install transformers
        run: |
          git clone https://github.com/huggingface/transformers
          cd transformers
          # if needed switch to the last known good SHA until transformers@master is fixed
          # git checkout 1cc453d33
          git rev-parse --short HEAD
          python3 -m pip install .

      - name: Install deepspeed
        run: |
          python3 -m pip install docutils==0.18.1 jinja2==3.0 urllib3==1.26.11
          python3 -m pip install .[dev,1bit,autotuning]
          ./bin/ds_report

      - name: Python environment
        run: |
          python3 -m pip list
