name: nv-h100

on:
  push:
    branches:
      - 'staging**'
    paths-ignore:
      - 'docs/**'
      - 'blogs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'blogs/**'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: [self-hosted, nvidia, h100]

    steps:
      - uses: actions/checkout@v3

      - name: Nvidia SMI
        run: |
          nvidia-smi -L
